#ifndef __STATUS_HPP__
#define __STATUS_HPP__

typedef enum
{
    SUCCESS_CODE,
    ERR_POINT_DOESNT_EXIST,
    ERR_TWO_POINTS_EQUAL,
    ERR_INVALID_POINT,
    ERR_EMPTY_POINTS,
    ERR_EMPTY_SCENE,
    ERR_UNDEFINED,
    ERR_FIGURE,
    ERR_TABLE,
    ERR_ARGS,
    ERR_FILE,
    ERR_DATA,
    ERR_IO
} status_t;

#endif